#!/bin/bash
#
# Perform necessary private-chef setup steps after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
        echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
        exit 1
}

ln -sf /opt/opscode/bin/private-chef-ctl /usr/bin || error_exit "Cannot link private-chef-ctl in /usr/bin"

if [ -e /etc/opscode/chef-server-running.json ]; then
  echo -e "\033[1mYou have upgraded Private Chef!\033[0m"
  echo
  echo
  echo "Now, edit the file:"
  echo
  echo "  /opt/opscode/embedded/cookbooks/private-chef/attributes/default.rb"
  echo
  echo "and set the value of the attribute:"
  echo
  echo "  default['private_chef']['opscode-chef-mover']['enable']"
  echo
  echo -e "to \033[1;31mtrue\033[0m."
  echo
  echo "The next step in the upgrade process is to run:"
  echo
  echo -e "\033[1;31mprivate-chef-ctl upgrade\033[0m"
  echo
  echo "When you are satisfied with the state of your system, "
  echo "you can remove configuration files, logs, directories,"
  echo "users, data, etc. that were used by internal services that"
  echo "have been removed from this version of Private Chef,"
  echo "by running runing:"
  echo
  echo -e "\033[1;31mprivate-chef-ctl cleanup\033[0m"
  echo
  echo "(Add the '--no-op' option to see what would be removed by"
  echo "this command)"
  echo
  echo "Finally, disable the 'opscode-chef-mover' service by setting"
  echo -e "the attribute you edited above back to \033[1;31mfalse\033[0m"
  echo "and running 'private-chef-ctl reconfigure'."
else
  echo -e "\033[1mThank you for installing Private Chef!\033[0m"
fi

exit 0
